// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tasngulhjhmjoxwebwky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhc25ndWxoamhtam94d2Vid2t5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwNzI3NzQsImV4cCI6MjA3NTY0ODc3NH0.YlaYK7ZKEMhO0p3VZ-PjAZDf3NgvgFmI-qQd0xtjdtg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});